### ISSUE TITLE
Make data in items update reactively

### ISSUE THREAD

**Issue by Treora** [Treora/cothink#17]
Content in displayed items should update when changed in the database.
As noted as `todo` on [this line](https://github.com/Treora/cothink/blob/6688f17220276c8833b8a402bb7112fc707b9172/cothink/client/cothink.js#L39)

**Comment by benkelaar** [comment]
Not only the content, but also the layout should respond reactively to changes in the data model, which is then a combination of client side state (what is the focussed item, which items are visible) and database state.

**Comment by Treora** [comment]
Good point. This might require more thought, but I guess that for now we'll just try to show each that is connected to the currently focussed item or something simple like that. (let's discuss sometime)

**Comment by Treora** [comment]
I made the basic content editing reactive now (2f5bb65 up to 11062e5). Had to use a separate editor and display node (a textarea and a div now), as an editable div caused trouble with Meteor's reactive updating, making edited content appear twice in the div.
Layout reactivity still needs to be addressed, but I'll leave that for another issue and close this one now (even if only for the rewarding feeling!).
